[workspace]
members = [
    "arch",
    "b2sum",
    "base32",
    "base64",
    "cat",
    "basename",
    "dirname",
    "echo",
    "env",
    "wc",
    "whoami",
]

[workspace.dependencies]
clap = { version = "4.0", features = ["derive"] }
